name: run-tests
on: 
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]
    
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter analyze && flutter test
